### ISSUE TITLE
doesn't build in FreeBSD 11.2 - AccessLog.cpp

### ISSUE THREAD

**Issue by lisergey** [xmrig/xmrig-proxy#306]
/home/miner/xmrig-proxy-2.14.0/> mkdir build; cd build; cmake .. 
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/local/lib/libuv.a  
-- Found OpenSSL: /usr/local/lib/libcrypto.so (found version "1.0.2r")  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/local/lib/libmicrohttpd.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/miner/xmrig-proxy-2.14.0/build

/home/miner/xmrig-proxy-2.14.0/build/> make
<skip>
[ 42%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/AccessLog.cpp.o
/home/miner/xmrig-proxy-2.14.0/src/log/AccessLog.cpp:72:130: error: cannot pass object of non-trivial type 'const xmrig::String' through variadic method; call will abort at runtime [-Wnon-pod-varargs]
            write("#%" PRId64 " login: %s, \"%s\", ua: \"%s\", count: %" PRIu64, e->miner()->id(), e->miner()->ip(), e->miner()->user(), e->miner()->agent(), Counters::miners());
                                                                                                                                 ^
/home/miner/xmrig-proxy-2.14.0/src/log/AccessLog.cpp:72:150: error: cannot pass object of non-trivial type 'const xmrig::String' through variadic method; call will abort at runtime [-Wnon-pod-varargs]
            write("#%" PRId64 " login: %s, \"%s\", ua: \"%s\", count: %" PRIu64, e->miner()->id(), e->miner()->ip(), e->miner()->user(), e->miner()->agent(), Counters::miners());
                                                                                                                                                     ^
/home/miner/xmrig-proxy-2.14.0/src/log/AccessLog.cpp:85:67: error: cannot pass object of non-trivial type 'const xmrig::String' through variadic method; call will abort at runtime [-Wnon-pod-varargs]
                  e->miner()->id(), e->miner()->ip(), e->miner()->user(), time, e->miner()->rx(), e->miner()->tx(), Counters::miners());
                                                                  ^
3 errors generated.
*** Error code 1

**Comment by lisergey** [comment]
but it does compile under gcc8

/> gcc8 --version
gcc8 (FreeBSD Ports Collection) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.

it would be nice to 'fix' this.
xmrig is being nicely compiled by clang

**Comment by xmrig** [comment]
Fixed in dev branch.
Thank you.

**Comment by DeadManWalkingTO** [comment]
I think this issue can be closed.
Thank you!
